$(document).ready(function(){
    $("#tech_corporate").css({"display":"none"});
    $("#event_description").css({"display":"none"});
    $("#rounds").css({"display":"none"});
    $("#judging_criteria").css({"display":"none"});
    $("#register").css({"display":"none"});
    $("#contact").css({"display":"none"});
    $("#show_tech_corporate").click(function(){
        $("#tech_corporate").css({"display":"table"});
        $("#introduction").css({"display":"none"});                    
        $("#event_description").css({"display":"none"});
        $("#rounds").css({"display":"none"});
        $("#judging_criteria").css({"display":"none"});
        $("#register").css({"display":"none"});
        $("#contact").css({"display":"none"});
    });
    $("#show_introduction").click(function(){
        $("#tech_corporate").css({"display":"none"});
        $("#introduction").css({"display":"table"});                    
        $("#event_description").css({"display":"none"});
        $("#rounds").css({"display":"none"});
        $("#judging_criteria").css({"display":"none"});
        $("#register").css({"display":"none"});
        $("#contact").css({"display":"none"});
    });
    $("#show_event_description").click(function(){
        $("#tech_corporate").css({"display":"none"});
        $("#introduction").css({"display":"none"});                    
        $("#event_description").css({"display":"table"});
        $("#rounds").css({"display":"none"});
        $("#judging_criteria").css({"display":"none"});
        $("#register").css({"display":"none"});
        $("#contact").css({"display":"none"});
    });
    $("#show_rounds").click(function(){
        $("#tech_corporate").css({"display":"none"});
        $("#introduction").css({"display":"none"});
        $("#event_description").css({"display":"none"});
        $("#rounds").css({"display":"table"});
        $("#judging_criteria").css({"display":"none"});
        $("#register").css({"display":"none"});
        $("#contact").css({"display":"none"});
    });
    $("#show_judging_criteria").click(function(){
        $("#tech_corporate").css({"display":"none"});
        $("#introduction").css({"display":"none"});                    
        $("#event_description").css({"display":"none"});
        $("#rounds").css({"display":"none"});
        $("#judging_criteria").css({"display":"table"});
        $("#register").css({"display":"none"});
        $("#contact").css({"display":"none"});
    });
    $("#show_register").click(function(){
        $("#tech_corporate").css({"display":"none"});
        $("#introduction").css({"display":"none"});                    
        $("#event_description").css({"display":"none"});
        $("#rounds").css({"display":"none"});
        $("#judging_criteria").css({"display":"none"});
        $("#register").css({"display":"table"});
        $("#contact").css({"display":"none"});
    });
    $("#show_contact").click(function(){
        $("#tech_corporate").css({"display":"none"});
        $("#introduction").css({"display":"none"});                    
        $("#event_description").css({"display":"none"});
        $("#rounds").css({"display":"none"});
        $("#judging_criteria").css({"display":"none"});
        $("#register").css({"display":"none"});
        $("#contact").css({"display":"table"});
    });
});